version: '3.7'

services:
  tourist-points-db:
    container_name: tourist-points-db
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=tourist-points
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123

    ports:
      - 35432:5432

    networks:
      - tourist-points-net

  pgadmin:
    container_name: tourist-points-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=AdminPostgres

    ports:
      - 18080:80

    networks:
      - tourist-points-net



networks:
  tourist-points-net:
